steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/clamav-scanner:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/clamav-scanner:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'clamav-scanner'
  - '--image'
  - 'gcr.io/$PROJECT_ID/clamav-scanner:latest'
  - '--no-allow-unauthenticated'
  - '--service-account'
  - 'clamav-scanner@development-344423.iam.gserviceaccount.com'
  - '--memory'
  - '4Gi'
  - '--min-instances'
  - '1'
  - '--max-instances'
  - '5'
  - '--cpu-boost'
  - '--region'
  - 'us-central1'
  - '--project'
  - '$PROJECT_ID'
  - '--set-env-vars'
  - 'CVD_MIRROR_BUCKET=cvd-mirror-development-344423'
