steps:
  - name: '${_GCR_HOSTNAME}/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - "${_GCR_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"
      - '-t'
      - '${_GCR_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - 'cloudrun-malware-scanner/Dockerfile'
      - 'cloudrun-malware-scanner'
  - name: '${_GCR_HOSTNAME}/cloud-builders/docker'
    args:
      - 'push'
      - "${_GCR_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"
  - name: '${_GCR_HOSTNAME}/cloud-builders/docker'
    args:
      - 'push'
      - '${_GCR_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}:latest'
  - name: '${_GCR_HOSTNAME}/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - 'run'
      - 'services'
      - 'udpate'
      - '${_SERVICE_NAME}'
      - "--image=${_GCR_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"
      - '--no-allow-unauthenticated'
      - '--cpu-boost'
      - '--region=${_REGION}'
      - '--platform=${_PLATFORM}'
substitutions:
  _REGION: "us-central1"
  _SERVICE_NAME: "clamav-scanner"
  _GCR_HOSTNAME: "us.gcr.io"
  _PLATFORM: "managed"
