steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build -t'
      - 'gcr.io/$PROJECT_ID/clamav-scanner:'$(date +'%Y%m%d')'-$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clamav-scanner:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clamav-scanner:'$(date +'%Y%m%d')'-$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clamav-scanner:latest'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'clamav-scanner'
      - '--image=gcr.io/$PROJECT_ID/clamav-scanner:'$(date +'%Y%m%d')'-$COMMIT_SHA'
      - '--no-allow-unauthenticated'
      - '--cpu-boost'
      - '--region=${_REGION}'
      - '--platform=managed'
substitutions:
  _REGION: "us-central1"
  _CVD_MIRROR_BUCKET: ""
